imports:
- path: phweb-instance-nfs.jinja
- path: phweb-kubernetes.jinja
- path: phweb-instance-cromwell.jinja

resources:
- name: phweb-instance-nfs-template
  type: phweb-instance-nfs.jinja
  properties:
    release: userresults
    environment: development
    nfsDiskSizeGb: 2000
    serviceAccount: 1021318262546-compute@developer.gserviceaccount.com
    classification: green
    ipAddress: 10.132.0.38

- name: phweb-instance-cromwell-template
  type: phweb-instance-cromwell.jinja
  properties:
    release: userresults
    environment: development
    serviceAccount: 1021318262546-compute@developer.gserviceaccount.com
    ipAddress: 10.132.0.92
    classification: green

- name: phweb-kubernetes-template
  type: phweb-kubernetes.jinja
  properties:
    release: userresults
    environment: development
