imports:
- path: phweb-instance-nfs.jinja
- path: phweb-kubernetes.jinja

resources:
- name: phweb-instance-nfs-template
  type: phweb-instance-nfs.jinja
  properties:
    release: userresults
    environment: production
    nfsDiskSizeGb: 2000
    serviceAccount: 1021318262546-compute@developer.gserviceaccount.com
