apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pheweb-front
  labels:
    app: pheweb
    tier: frontend
spec:
  serviceName: pheweb-front
  selector:
    matchLabels:
      app: pheweb
  replicas: 3
  template:
    metadata:
      labels:
        app: pheweb
        tier: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pheweb
            topologyKey: kubernetes.io/hostname
      containers:
      - name: pheweb-container
        image: gcr.io/phewas-development/pheweb:ci-ae99dcf60b3a960366af0cf9b4e0a7626b3f8fbb
        env:
        - name: PHEWEB_DIR
          value: "/mnt/nfs/pheweb/r6"
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            path: /health
            port: 8080
        volumeMounts:
        - mountPath: /mnt/nfs
          name: pheweb-nfs
      volumes:
      - name: pheweb-nfs
        persistentVolumeClaim:
          claimName: nfs-claim
          readOnly: false
