apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pheweb-front
  labels:
    app: pheweb
    tier: frontend
spec:
  serviceName: pheweb-front
  selector:
    matchLabels:
      app: pheweb
  replicas: 2
  template:
    metadata:
      labels:
        app: pheweb
        tier: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pheweb
            topologyKey: kubernetes.io/hostname
      containers:
      - name: pheweb-container
        image: gcr.io/phewas-development/pheweb:r4_10
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /mnt/nfs
          name: pheweb-nfs
      volumes:
      - name: pheweb-nfs
        persistentVolumeClaim:
          claimName: nfs-claim
          readOnly: false
