# Default values are found in values.yaml

image:
  tag: ci-f7490aec688bb4cdebd3555f08409552d6b3eac1

persistentVolume:
  path: /data/nfs/pheweb
  server: 10.132.0.38

pheweb:
  cloudSQLCredentialFile: /etc/gcp/cloud-sql-credentials.json
  cloudSQLProxyInstances: phewas-development:europe-west1:dev-db1=tcp:3306
  directory: /mnt/userresults/release
  ipName: finngen-userresults-old-ip
  mount: /mnt
  release: userresults
  secretName: development-userresults-secrets
  subdomain: userresults-old

replicaCount: 2
